coverage:
  range: 80..100
  round: up
  precision: 2

  status:
    project:
      default:
        threshold: 5%

    patch:
      default:
        branches:
          - master

parsers:
  javascript:
    enable_partials: yes
