sudo: required
services:
  - docker
script:
  - >
    TRAVIS=$TRAVIS
    TRAVIS_COMMIT=$TRAVIS_COMMIT
    TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER
    TRAVIS_BRANCH=$TRAVIS_BRANCH
    TRAVIS_JOB_ID=TRAVIS_JOB_ID
    TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
    TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG
    docker run -v $(pwd):/var/app kuzzleio/lb-test /var/app/bin/run-test-travis.sh
notifications:
  email: false